// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/EliasEMC/rickpoke-poc/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// CharacterFetcher is an autogenerated mock type for the CharacterFetcher type
type CharacterFetcher struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CharacterFetcher) GetByID(ctx context.Context, id int) (*model.Rick, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Rick
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.Rick, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.Rick); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Rick)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCharacterFetcher creates a new instance of CharacterFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCharacterFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *CharacterFetcher {
	mock := &CharacterFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
