// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/EliasEMC/rickpoke-poc/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// PokemonFetcher is an autogenerated mock type for the PokemonFetcher type
type PokemonFetcher struct {
	mock.Mock
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *PokemonFetcher) GetByName(ctx context.Context, name string) (*model.Pokemon, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *model.Pokemon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Pokemon, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Pokemon); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pokemon)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPokemonFetcher creates a new instance of PokemonFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPokemonFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PokemonFetcher {
	mock := &PokemonFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
